module.exports = [
    {
        name: 'bootstrap',
        files: [
            {
                src: 'node_modules/bootstrap/dist/css/bootstrap.min.css',
                dest: 'bootstrap.min.css'
            },
            {
                src: 'node_modules/bootstrap/dist/js/bootstrap.bundle.min.js',
                dest: 'bootstrap.bundle.min.js'
            }
        ]
    },

    {
        name: 'jquery',
        files: [
            {
                src: 'node_modules/jquery/dist/jquery.min.js',
                dest: 'jquery.min.js'
            }
        ]
    },

    {
        name: 'moment',
        files: [
            {
                src: 'node_modules/moment/min/moment.min.js',
                dest: 'moment.min.js'
            }
        ]
    },

    {
        name: 'lodash',
        files: [
            {
                src: 'node_modules/lodash/lodash.min.js',
                dest: 'lodash.min.js'
            }
        ]
    },
     {
        name: 'jquery-validation',
        files: [
            {
                src: 'node_modules/jquery-validation/dist/jquery.validate.min.js',
                dest: 'jquery.validate.min.js'
            },
            {
                src: 'node_modules/jquery-validation/dist/additional-methods.min.js',
                dest: 'additional-methods.min.js'
            }
        ]
    },
    {
        name:"datatables",
        files: [
            {
                src:"node_modules/datatables.net/js/dataTables.min.js",
                dest:"dataTables.min.js"
            },
            {
                src:"node_modules/datatables.net-bs5/css/dataTables.bootstrap5.min.css",
                dest:"dataTables.bootstrap5.min.css"
            },
            {
                src:"node_modules/datatables.net-bs5/js/dataTables.bootstrap5.min.js",
                dest:"dataTables.bootstrap5.min.js"
            }
        ]
    },
    {
        name:"datepicker",
        files:[
            {
                src:"node_modules/vanillajs-datepicker/dist/js/datepicker-full.min.js",
                dest:"datepicker-full.min.js"
            },
            {
                src:"node_modules/vanillajs-datepicker/dist/css/datepicker.min.css",
                dest:"datepicker.min.css"
            },
            {
                src:"node_modules/vanillajs-datepicker/dist/css/datepicker-bs5.min.css",
                dest:"datepicker-bs5.min.css"
            }
        ]
    }

];